apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-stouffcapital-website
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - stouffcapital.com
    - www.stouffcapital.com
    secretName: stouffcapital-service-tls
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: stouffcapital.com
    http:
      paths:
      - path: /
        backend:
          serviceName: stouff-capital-website
          servicePort: 80
  - host: www.stouffcapital.com
    http:
      paths:
      - path: /
        backend:
          serviceName: stouff-capital-website
          servicePort: 80

